### ISSUE TITLE
Todo: Missing features

### ISSUE THREAD

**Issue by Thesola10** [nixie-dev/nixie#4]
These are features that I intend to add to Nixie, but haven't gotten around to yet.

Some of these features' description may not cover all the information needed to implement them, but that is not a mistake.

- [x] `.gitignore` and `.gitattributes` should be set up
- [ ] Implement project templates
- [x] `--nixie-*` command line options
- [x] Choose `nix` or `nix-shell` filename depending on other `.nix` files
- [ ] Check if local `nixpkgs`/`nixos` channel is more recent on `update`
